### ISSUE TITLE
[Feat] 로딩, 오류, Api mocking 처리 방법 추가

### ISSUE THREAD

**Issue by seongbin9786** [BoardSignal/Team-CivilWar-BoardSignal-FE#79]
## 🤷‍♂️ 내용 요약

사용 가이드 및 작업 내용 안내는 작성해서 공유하겠습니다 :)

- 작업 내용 안내
  - React-query 환경에서 효율적으로 오류 처리하기 https://jsqna.vercel.app/efficient-error-handling-in-react-query
  - 예시로 배우는 msw API mocking https://jsqna.vercel.app/api-mocking-with-msw-by-example
---

#### Task

- [x] 로딩 컴포넌트를 추가해요: `Spinner`, `SpinnerFullScreen`
- [x] 로딩 컴포넌트의 스토리를 추가해요: `Spinner`, `SpinnerFullScreen`

#### 사용법 (제안 사항)
- `useQuery + isPending` 대신 `<Suspense> + useSuspenseQuery`를 사용해요.
- 로딩 화면이 필요한 곳에는 `<Suspense>`로 감싸주세요.

---

#### Task

- [x] 오류 화면을 표시하는 컴포넌트를 추가해요 `ErrorAlertFullScreen`
- [x] 로딩 컴포넌트의 스토리를 추가해요: `ErrorAlertFullScreen`
- [x] 오류 컴포넌트를 추가해요: `ErrorBoundary`, `ApiErrorBoundary`
- [x] axios.get을 제외한 mutation API의 경우 `data`가 아니라 `{ status, data }`를 반환해요.
- [x] 비동기 콜백의 오류도 공통으로 처리하기 위한 커스텀 훅을 만들어요. (`useErrorBoundary`)
- [x] Toast를 띄우기 위해 `react-hot-toast`를 설치하고, error 토스트의 스타일을 커스터마이징했어요.

#### 사용법 (제안 사항)

- `isError`를 대신 `<ErrorBoundary>`를 사용해요.
- 오류 발생 시 안내 화면이 필요한 곳에는 `<ApiErrorBoundary>`로 감싸주세요.
- 이벤트 핸들러 등 비동기 콜백의 오류를 공통 처리하려면 `passError`로 감싸주세요.
- useMutation 시 `data`가 아니라 `{ status, data }`를 받아요. (자동으로 타입을 잡아줘요)
- Error Toast를 띄울 때는 `showErrorToast` 함수를 사용해주세요.

---

#### Task

- [x] 개발 환경에서 `VITE_USE_MSW=true`인 경우에 msw를 실행하는 로직을 추가해요
- [x] msw에 개발 리소스 등의 요청을 무시하는 로직을 추가해요.
- [x] msw에 기본적인 서버 딜레이를 추가해요.
- [x] msw를 사용하는 기본 예제를 추가해요. (`notifications`)

#### 사용법 (제안 사항)

- `mocks` 폴더를 사용해요.
- `.env` 파일에 `VITE_USE_MSW=true`를 추가해요.
- API를 요청하는 Story는 mock을 사용해서 화면을 재현해주세요.
